---
title: "CalU evaluation and assignments"

---





A) Exams: There will be 3 exams including the final. Exams will include 
i) an in-class portion that will use short answer questions to test your understanding of the material, with potentially some true/false, matching, multiple choice, etc.  Even if question are T/F or multiple choice they will questions will mostly involve “word problems”, interpretation of numeric and graphical results, and interpretation of output from the statistical software R.  The in-class portion will focus on concepts but may require short computations that can be done by hand (e.g., addition, subtraction, multiplication).  
ii) and/or a take-home portion consisting of problem sets.  Take-home tests will require computations to be done in the software R and the submission of results and figures.  

NOTE: Some material tested on the exams will be cumulative.  General concepts covered on the 1st test such as experimental design, random sampling, statistical independence, the definition of a p-value, best practices for visualizing data, as well as others, will re-appear on the 2nd two exams.  More specifically, you will be expected to interpret new material in light of concepts covered on the 1st test.  

2) Homework:  There will be ~13 homework assignments/problem sets focused on materials from the lecture and book that will be assigned approximately weekly.  These will primarily be based on questions from the book.  They may involve short answers and/or short computations in R.  A worksheet for filling out your answers will typically be provided as a hardcopy or digitally and must be used and submitted as a hard copy.  You will lose 5% of your points for not using the provided worksheet.  Student are encouraged to work on homework together but all answers must reflect their thoughts and computations.

Your lowest homework 3 scores will be dropped (i.e. 10 of the 13 will count towards your grade).  Equivalently, you can skip 3 assignments; however, you are highly encouraged to attempt all assignments.  Students must keep track of which assignments they have submitted.  Completion more than the required number of assignments will not result in extra credit.

Precise due dates will be set when the assignments are handed out; you will typically have 10 days to complete an assignment and assignments will be due at the start of Tuesday lab sessions.  You will lose 10% from you grade for each day it is late up until 10 days.  There will be no makeup assignments or extra credit.

3) Class Attendance, Participation, and In-class Activities:   Attendance during the lecture will be essential for ensuring your success in this course. There will be 8 in-class activities throughout the course and you must be present for 5 of these to receive full participation marks. These activities cannot be made up.  Participation in more than 5 will not result in extra credit.

4) Experimental Design & Writing Assignment: Over the course of the semester you will have an opportunity to write a short scientific paper.  Further details will be provided later in class.  For the final version of your paper you will be expected to incorporate the feedback received on your earlier submissions. 

5) Pre-lab Questions.  There will be ~14 sets of short pre-lab questions intended to prepare you for each weeks’ lab materials.  Your top 12 scores will count towards your grade. Students must keep track of which assignments they have submitted.  Completion of >12 will not count towards extra credit.

6) Lab Attendance & Engagement:  Attendance during the lab is mandatory and attendance will be recorded at the beginning of each lab.  Active engagement with the material is also necessary and you will be required to submit a digital log file from your computer demonstrating your work.

7) In-lab worksheets and assignments.  During each lab there will be a worksheet that will need to be completed based on calculations and/or work you complete during lab will also be uploaded to courseweb. 
