---
title: "Catalog description"

---

Original Pitt catalog description
This course provides students the knowledge on applications of statistical technique to biological problems. The data fit, regression analysis, significance of correlation coefficient and of standard error of estimate will be discussed. The binomial, normal, and Poisson distributions, the student's t-distribution and the chi-squared distribution will be introduced. Hypothesis testing, significance levels, confidence limits for large and small samples and non-para metric statistics will be covered. Basic computer programming (use of BMDP and statview) will be introduced.


Duq
Applied Biological Data Analysis & Statistics
The purpose of this course will be to provide a solid background in the core concepts of applied biological statistics, the use of the software R for data analysis and the use of RMarkdown for documenting reproducible analyses.  The course will review basic statistical concepts, thoroughly cover contemporary linear regression and analysis of variance (ANOVA), and introduce the advanced concepts of generalized linear models (GLMs) such as logistic regression and mixed effect models.  
R is the current lingua franca of many users and developers of statistical techniques and its use will therefore play a central role in the course from the first day of class.  Basic statistical concepts will be reviewed by carrying out mathematical calculations step-by-step in R, and the application and interpretation of all techniques will be presented with direct reference to the necessary R code and the resulting R output.  Each class will be a mix of lecture and guided R exercises.  Throughout the course important aspects of experimental design will be emphasized, such as true replication vs. pseudoreplication, random sampling, and blocking.  The course will also teach the skills necessary to manage, summarize, and graphically display data.  

Duq - course catalog?
Biostatistics is the application of statistical principals to the design and analysis of biological studies.  This course covers the methods, software, theory, and philosophy used in contemporary biostatistics.  Examples will be drawn from across biological disciplines, including ecology, physiology, genomics cell, and molecular biology.  Topics covered include basic data science and visualization, hypothesis testing and model building, analysis of variance (ANOVA), linear regression, multivariate statistics, power analysis, and experimental design.  Emphasis is placed on actively using the software R to apply these methods to real biological data.