---
title: "Duq assessment"
---

Evaluation: Students will be evaluated through participation, weekly assignments, two group assignments, and an independent project related to their own work.

Weekly assignments: Student will be given weekly data visualization and analysis assignments to be completed in R.  Assignments will be typically be based on chapters from the assigned text, Intuitive Biostatistics.

Group assignments: Students will work in pairs on two extended homework assignments.  The first will be an extended analysis of data from one of the chapters from the text, and the second will be a re-analysis of results from a published study.

Independent Project:  Each student will identify a dataset and carry out an independent investigation, culminating in a draft of short scientific paper focused on the methods and results section, and appropriate graphs, tables and appendices.  The project will be split into 3 parts.  Early in the semester students will be required to submit a proposal outlining the dataset they wish to use and the scientific question of interest.  By mid-term students will submit an outline of the introduction, a methods section, and initial descriptive statistics and exploratory graphs of their data.  The final paper will consists of a complete scientific manuscript, though the introduction and discussion need only to briefly outline the biological questions and conclusions.  Students are encouraged to use data from their own research or obtain data from their advisor.  I can also discuss with students data sets that I have from my forest ecology and avian ecology work.  Students are encouraged to work collaboratively in determining the appropriate analysis approaches and to help each other with their R code, but each student must analyze a separate data set.


