---
title: "Biostatistics Independent Project - Assignment 3 - Scientific Question & Analysis Proposal"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

|BioSCI 1120
|Independent Research Project 

* xx Points (10% of total points for paper)
* Assigned: 
* Due:

## Introduction 

The goal of this assignment is for students to write up the important basic details related to their research question/hypothesis, and how their statistical methods relate to that question.  This will form the seeds of the subsequent introduction and statistical methods section of their paper.


## Assignment: What, Why & How

Submit a 1-2 page double-spaced document with the sections outlined below.  Make each section a separate **bold** heading.  These sections relate to the basic questions: what, why, and how.  I’ve included guidelines for the approximate number of sentences that I think you should be able to accomplish this in.  This material is oriented towards datasets generated by experiments but other types of data can be used. 

1.  **Problem/Question statement (“What”)**: State the overall questions you are interested, hypothesis you wish to test, or what you want to learn from the dataset.  The research question can evolve over time but a starting point needs to be defined.  (1-3 Sentences)
1. **Question statement / Statement of importance (“Why is this interesting?”)**  State the broad scientific question of interest and why it is interesting to i) you and to ii) science or society.  (1-3 sentences; **provide 1-2 citations**).
1.  **Statistical Methods (“How will the data be analyzed”)** A brief outline, to the best of your ability, of the how the data will be analysed.  This should include statement of the **response variable (y)** and the **predictor variables (x)** and what type of variable each on is (continuous, categorical, binary, count, etc).  Also, if possible, indicate the **type of analysis** you think might be used (regression, ANOVA, logistic regression).  If you don't know, that's fine, but make your best guess.
1.  **References**  You must cite at least 2 references within this assignment and provide full bibliographic information.  At least 1 of the references must occur in your **Problem/Question Statement** or **Statement of Importance** (such as a reference about why this question is interesting).  The 2nd reference can be in any of the 3 parts; for example, you can provide a reference to a study that uses a statistical approach you think you will use.   References should be from peer reviewed journals (i.e. Aquatic Ecology, Journal of Wildlife Management, Cell, Nature).  Newspapers, magazine articles, websites etc. are not permitted.  Citations should be formatted as below, which is typical for ecological and environmental journals.

### Example Reference:

**In-text citation:**
“White-tailed deer browse is known to slow regeneration of some forest species, which can then impact wildlife than depend on those plants (DeCalesta 1994). “

**Reference:**
DeCalesta, D. 1994. Effect of white-tailed deer on songbirds within managed forests in Pennsylvania. Journal of Wildlife Management 58:711–718.