---
title: "Biostatistics Independent Project - Assignment 2 - Data Description"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

|BioSCI 1120
|Independent Research Project 

* xx Points (10% of total points for paper)
* Assigned: 
* Due:

## Introduction 

The overall goal of the independent research project is to have each student lead an independent scientific investigation.  Using these data, students will analyze and report the results of their study using the analysis skills learned in this class.  The goal of this assignment is for students to write up the important basic details related to how their data where generated.  This will form the seeds of the subsequent methods section of the paper.


## Assignment Details: How, where, when, who

Submit a 1-2 page double-spaced proposal with the sections outlined below (can be less, as long as all details are present).  Make each section a separate **bold** heading.  These sections address the basic questions: Who, what, where, when, why, and how.  I’ve included guidelines for the approximate number of sentences that I think you should be able to accomplish this in.  This material is oriented towards datasets generated by experiemnts but other types of data can be used. 

1.  **Field/Lab Methods (“How was data obtained”)** A brief outline of the experimental set up, sampling design, etc that generated the data.  Details can include a description of the overall approach (eg randomized behavioral experiment), methodology (simulation of protein dynamics), sampling plan for field data (eg transect sampling), how the database was constructed etc (government program, citizen science).  (Short paragraph;  provide reference if relevant, such as to the database where the data are from).
1.  **Study site / Experimental set up  (“Where was the data collected”)** Provide a brief description with additional details about where / how the data were or are collected.  For field data, indicate where the data were collected; for lab data, provide additional information about the specific experimental set up.  For data from a database, provide additianl information about how the data was collated or who maintains it.  (1-3 sentences)
1.  **Timeline (“When will data be obtained”)**  If data is not currently in-hand, a brief timeline for the implementation of the project or acquisition of the data (when you will start, how long it will take, etc.  This is most important if the data have not yet all been collected or from a database that has not yet been accessed.)
1.  **Feasibility (“How will project get completed”)** A brief discussion of feasibility and potential problems you may encounter (i.e, the experiment is still in progress and plants must grow, biological materials still need to be obtained, you have never accessed the database before and might need help with data preparation, etc).  (1 sentence to short paragraph)
1.  **Collaborators (“Who is involved”)**  State if you will be collaborating with anyone from this class, your lab etc and what their role is.    
1.  **References**  You must cite at least 2 references within your proposal and provide full bibliographic information.  If you are basing your methods on established protocols you can put one of your citations in the **Field/Lab Methods** section (copy from previous assignment).  If you are working at a site where work has been done previously you can provide a citation in your **Study site** description.  If you are using a published database locate an official citation for the database and provide a citation containing the URL of the data itself.  For example, many databases have a peer reviewed paper in a journal describing the database.  This would be a seperate citation from the website/database itself.  

## More info on reference

References should be from peer reviewed journals (i.e. Aquatic Ecology, Journal of Wildlife Management, Cell, Nature) or official government reported (“white papers” or the “grey literature”).  A paper on the general topic are that conducts a similar analysis is also acceptable.  Newspapers, magazine articles, websites, b;pgs etc. are not permitted without permission.  Citations should be formatted as below, which is typical for journals in the biological sciences.  Similar formats that provide full citation information will also be accepted if they are standard for a different field or target journal; the formatt used ins Science / Nature / PNAS etc is too short and not acceptable.


## Assessment 

Assessment for Assignment 1 will be based on whether the proposal contains the major elements in the assignment, which generally are meant to answer he questions “Who, where, why, and how.”  Inclusion of the major details will result in full credit.

## Assignment Formatting

* The proposal should be ~2 double spaced pages with a standard font (eg Calibri, Times New Roman, Arial), font size (11 or 12) and margins (1 inch).  
* The proposal should include each of the sections outlined above.
* The proposal must include 2 references, one of which must occur in the Problem Statement.

## References / Citations

### Normal papers

**In-text citation:**
“White-tailed deer browse is known to slow regeneration of some forest species, which can then impact wildlife than depend on those plants (DeCalesta 1994). “

**Reference:**
DeCalesta, D. 1994. Effect of white-tailed deer on songbirds within managed forests in Pennsylvania. Journal of Wildlife Management 58:711–718.

### Data stored on Github

A citation for a github page might look likethis:

P.W.D. Charles, Project Title, (2013), GitHub repository, https://github.com/charlespwd/project-title


(see discussion here  https://academia.stackexchange.com/questions/14010/how-do-you-cite-a-github-repository)


### Blogs (with approval only)
If you end up needing to cite a blog (only with approval) it might look like this:

Author’s Last Name, Author’s First Name. “Title of Post.” Blog Name, Publisher (only include this information if it is different than the name of the blog site), Date blog post was published, Link to post (omit http:// or https://).

For more info on citing blogs See info here http://www.easybib.com/guides/how-to-cite-a-blog-mla-apa-chicago/



